import { z } from "zod";
import { Agent, AgentInputItem, Runner, withTrace } from "@openai/agents";
import { OpenAI } from "openai";
import { setDefaultOpenAIClient } from "@openai/agents";
import "dotenv/config";

const myClient = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

setDefaultOpenAIClient(myClient);

const SummarySchema = z.object({ patient_profile: z.object({ medical_history: z.array(z.string()), allergies: z.array(z.string()), medications: z.array(z.string()), lifestyle: z.array(z.string()), surgical_history: z.array(z.string()) }), current_complaints: z.array(z.string()), symptom_details: z.object({ location: z.string(), duration: z.string(), severity: z.string(), triggers: z.string(), associated_symptoms: z.array(z.string()) }), questions_asked_by_doctor: z.array(z.string()), patient_answers: z.array(z.string()), suspected_conditions: z.array(z.string()), conversation_summary: z.string() });
const summary = new Agent({
  name: "Summary",
  instructions: `You are a Medical Conversation Memory Agent.

Your job is to maintain a concise but complete summary of the medical conversation between a patient and the AI doctor.

You will receive:
1. The previous conversation summary (if available)
2. The latest conversation messages between the patient and doctor
3. Any AI-generated diagnostic outputs (suspected causes, questions asked, etc.)

Your task is to update the summary so that future medical analysis agents can understand the full context quickly.

Guidelines:
- Preserve important medical details.
- Include symptoms, duration, severity, and affected body parts.
- Include questions asked by the AI doctor.
- Include answers given by the patient.
- Include suspected causes generated by the diagnosis agent.
- Track patient medical history, medications, allergies, and lifestyle if mentioned.
- Remove repeated or unnecessary conversational text.
- Keep the summary structured and compact.

Output format MUST be valid JSON.

JSON structure:

{
  \"patient_profile\": {
    \"medical_history\": [],
    \"allergies\": [],
    \"medications\": [],
    \"lifestyle\": [],
    \"surgical_history\": []
  },
  \"current_complaints\": [],
  \"symptom_details\": {
    \"location\": \"\",
    \"duration\": \"\",
    \"severity\": \"\",
    \"triggers\": \"\",
    \"associated_symptoms\": []
  },
  \"questions_asked_by_doctor\": [],
  \"patient_answers\": [],
  \"suspected_conditions\": [],
  \"conversation_summary\": \"\"
}

Rules:
- Merge the previous summary with the new conversation.
- Never remove medically relevant information.
- Avoid duplicating entries.
- Keep the conversation summary under 200 words.
- Return ONLY JSON.`,
  model: "gpt-4o",
  outputType: SummarySchema,
  modelSettings: {
    temperature: 1,
    topP: 1,
    maxTokens: 2048,
    store: true
  }
});

type WorkflowInput = { input_as_text: string };


// Main code entrypoint
export const summaryForLLM = async (workflow: WorkflowInput) => {
  return await withTrace("Summary for llm", async () => {
    const conversationHistory: AgentInputItem[] = [
      { role: "user", content: [{ type: "input_text", text: workflow.input_as_text }] }
    ];
    const runner = new Runner({
      traceMetadata: {
        __trace_source__: "agent-builder",
        workflow_id: "wf_69ae4e7a55608190bcb847ce418f3089023f1a2e27ad1827"
      }
    });
    const summaryResultTemp = await runner.run(
      summary,
      [
        ...conversationHistory
      ]
    );
    conversationHistory.push(...summaryResultTemp.newItems.map((item) => item.rawItem));

    if (!summaryResultTemp.finalOutput) {
        throw new Error("Agent result is undefined");
    }

    const summaryResult = {
      output_text: JSON.stringify(summaryResultTemp.finalOutput),
      output_parsed: summaryResultTemp.finalOutput
    };
    return summaryResult;
  });
}
